name: Commit cheat

on:
  workflow_dispatch:
  schedule:
    - cron: "45 * * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate content, commit, and push
        run: |
          git config --local user.email "mrismanaziz@gmail.com"
          git config --local user.name "mrismanaziz"
          
          echo "## $(curl -H "Accept: text/plain" https://icanhazdadjoke.com)" > README.md
          
          if ! git diff-index --quiet HEAD; then
            echo "✅ Perubahan terdeteksi, melakukan commit..."
            git add README.md
            COMMIT_MESSAGE=$(curl -s https://corporatebs-generator.sameerkumar.website/ | jq -r '.phrase')
            if [ -z "$COMMIT_MESSAGE" ]; then
              echo "⚠️ Gagal mendapatkan pesan commit acak, menggunakan pesan default."
              COMMIT_MESSAGE="auto-update README on $(TZ="Asia/Jakarta" date +"%H:%M:%S")"
            fi
            echo "Melakukan commit dengan pesan: $COMMIT_MESSAGE"
            git commit -s -m "$COMMIT_MESSAGE"
            git push --force
            echo "🚀 Perubahan berhasil di-push ke repositori."
          else
            echo "✅ Tidak ada perubahan pada file, commit dilewati."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
